name: gh-pages

on:
  push:
    branches:
      - rs

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: "12"

      - uses: icepuma/rust-action@master
        with:
          args: |
            cd generator
            cargo run ../editor/data/gta3-scl.json > ../editor/data/gta3_classes.db
            cargo run ../editor/data/vc-scl.json > ../editor/data/vc_classes.db

      - name: Build gh-pages
        run: |
          cd editor
          npm install
          npm run build
          cp data dist/editor -r
          cp src/404.html dist/editor
          echo "library.sannybuilder.com" > dist/editor/CNAME

      - name: Deploy gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./editor/dist/editor
