name: gh-pages

on:
  push:
    branches:
      - fix

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: "12"

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build gh-pages
        run: |
          cd editor
          npm install
          npm run build
          cp src/404.html dist/editor

      - name: Compile files
        run: |
          cd generator
          cargo run classes ../gta3/gta3.json > ../editor/dist/editor/assets/gta3/classes.db
          cargo run classes ../vc/vc.json > ../editor/dist/editor/assets/vc/classes.db
          cargo run snippets ../gta3/snippets > ../editor/dist/editor/assets/gta3/snippets.json
          cargo run snippets ../vc/snippets > ../editor/dist/editor/assets/vc/snippets.json

      - name: Deploy gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./editor/dist/editor
          cname: library.sannybuilder.com
