name: gh-pages

on:
  push:
    branches:
      - rs2

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: "12"

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Compile files
        run: |
          cd generator
          cargo run classes ../gta3/gta3.json > ../editor/data/gta3_classes.db
          cargo run classes ../vc/vc.json > ../editor/data/vc_classes.db
          cargo run snippets ../gta3/snippets > ../editor/data/gta3_snippets.json
          cargo run snippets ../vc/snippets > ../editor/data/vc_snippets.json

      - name: Build gh-pages
        run: |
          cd editor
          npm install
          npm run build
          cp data/* dist/editor/assets
          cp src/404.html dist/editor
          echo "library.sannybuilder.com" > dist/editor/CNAME

      - name: Deploy gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./editor/dist/editor
